<?php 
/**
 *
 *
 */

/**
 * Implements hook_menu().
 *
 * Creates the menu callback for the module admin page.
 */
function alert_menu() {
  $items['admin/config/content/alert'] = array(
    'title' => 'Alert - Custom Alert Message',
    'description' => 'Set a custom alert message',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alert_set_message_form'),
    'access arguments' => array('administer alerts'),
    'file' => 'alert.admin.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function alert_permission() {
  return array(
    'administer Alert' => array(
      'title' => 'Administer Bean No Title',
      'description' => 'Create an alert by leveraging drupal_set_message',
    ),
  );
}

/**
 * Implements hook_init().
 */
function alert_init() {
  if (drupal_is_front_page() && variable_get('alert_custom_message_contents') !== '<none>' || '') {
    drupal_set_message(variable_get('alert_custom_message_contents'), 'warning', FALSE);
  }
}
